<a href="https://colab.research.google.com/github/udtmhr/Othello/blob/main/tesorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import tensorflow as tf

In [15]:
#データの読み込み
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0 #ニューラルネットワークの入力は０～１の範囲が好ましいので正規化している

In [17]:
#モデルの作成
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [18]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.30723768, -0.29687044, -0.05416459, -0.4614042 ,  0.38315403,
         0.53537536,  0.20663312,  0.6195381 ,  0.35873026, -0.5200459 ]],
      dtype=float32)

In [19]:
tf.nn.softmax(predictions).numpy()

array([[0.06482883, 0.06550443, 0.08349807, 0.05556668, 0.12930088,
        0.15056026, 0.10837757, 0.16378035, 0.12618113, 0.05240187]],
      dtype=float32)

In [21]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn

In [22]:
model.compile(optimizer="adam",
              loss=loss_fn,
              metrics=["accuracy"])

In [23]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 8s 3ms/step - loss: 0.3022 - accuracy: 0.9111
Epoch 2/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1459 - accuracy: 0.9557
Epoch 3/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1089 - accuracy: 0.9677
Epoch 4/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0892 - accuracy: 0.9722
Epoch 5/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0765 - accuracy: 0.9765


In [24]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 1s - loss: 0.0764 - accuracy: 0.9780 - 699ms/epoch - 2ms/step


[0.0764191523194313, 0.9779999852180481]

In [25]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax(),
])

In [26]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.20759021e-08, 1.00795161e-09, 1.23604650e-05, 1.29755848e-04,
        3.58155888e-12, 2.29561046e-08, 3.19295719e-15, 9.99856710e-01,
        4.34307914e-08, 1.10425117e-06],
       [1.04987066e-07, 4.88445570e-04, 9.99384880e-01, 1.22899117e-04,
        5.08919587e-15, 3.19524474e-06, 4.39096937e-08, 8.95919352e-13,
        3.95417942e-07, 3.08481582e-12],
       [1.22873762e-05, 9.99382257e-01, 8.51727818e-05, 8.15237672e-06,
        2.12186587e-05, 1.65863385e-05, 8.77034909e-05, 2.18274101e-04,
        1.63994890e-04, 4.39340829e-06],
       [9.99965549e-01, 9.31028032e-11, 2.41648354e-06, 9.18374923e-08,
        1.08340082e-07, 7.70904080e-07, 4.70719397e-06, 2.06914374e-05,
        2.20178435e-08, 5.64396942e-06],
       [1.11720192e-05, 3.69826950e-07, 4.37975996e-06, 1.46429180e-08,
        9.98865366e-01, 1.87491750e-07, 1.36550889e-05, 2.41342670e-04,
        1.24516157e-06, 8.62215820e-04]], dtype=float32)>